version: '3.4'

networks:
  sharednetwork: 

services:
  sqlserverdb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      - sharednetwork
    ports:
      - "8002:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=admin@123
    volumes:
      - mssql_data:/var/opt/mssql  # Persistent storage for SQL Server data
      - ./init-db:/docker-entrypoint-initdb.d/ # Load data on startup

  puppy_project:
    build:
      context: .
      dockerfile: Puppy_Project/Dockerfile
    networks:
      - sharednetwork
    depends_on:
      - sqlserverdb
    ports:
      - "8001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserverdb;Database=puppyDb;User Id=sa;Password=admin@123;TrustServerCertificate=True;

volumes:
  mssql_data:
